/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "certificateHashes" | "storeHash" | "verifyHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateStored"): EventFragment;

    encodeFunctionData(functionFragment: 'certificateHashes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'storeHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyHash', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'certificateHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHash', data: BytesLike): Result;
  }

  
    export namespace CertificateStoredEvent {
      export type InputTuple = [hash: BytesLike, submitter: AddressLike];
      export type OutputTuple = [hash: string, submitter: string];
      export interface OutputObject {hash: string, submitter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: CertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    certificateHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    storeHash: TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyHash: TypedContractMethod<
      [hash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'certificateHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'storeHash'): TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyHash'): TypedContractMethod<
      [hash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CertificateStored'): TypedContractEvent<CertificateStoredEvent.InputTuple, CertificateStoredEvent.OutputTuple, CertificateStoredEvent.OutputObject>;

    filters: {
      
      'CertificateStored(bytes32,address)': TypedContractEvent<CertificateStoredEvent.InputTuple, CertificateStoredEvent.OutputTuple, CertificateStoredEvent.OutputObject>;
      CertificateStored: TypedContractEvent<CertificateStoredEvent.InputTuple, CertificateStoredEvent.OutputTuple, CertificateStoredEvent.OutputObject>;
    
    };
  }