/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { CertificateRegistry, CertificateRegistryInterface } from "../CertificateRegistry.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "submitter",
        "type": "address"
      }
    ],
    "name": "CertificateStored",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "certificateHashes",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      }
    ],
    "name": "storeHash",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      }
    ],
    "name": "verifyHash",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506101a48061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c80637fe8888514610043578063bedda47e14610058578063ef020f4a1461008e575b5f5ffd5b610056610051366004610157565b6100b0565b005b61007a610066366004610157565b5f6020819052908152604090205460ff1681565b604051901515815260200160405180910390f35b61007a61009c366004610157565b5f9081526020819052604090205460ff1690565b5f8181526020819052604090205460ff16156101125760405162461bcd60e51b815260206004820152601a60248201527f436572746966696361746520616c72656164792073746f726564000000000000604482015260640160405180910390fd5b5f81815260208190526040808220805460ff1916600117905551339183917f68c57ee07187efc88a54ed1e3d4105b6e7d0f49dcb887c87bb1caca9bf2c0ce59190a350565b5f60208284031215610167575f5ffd5b503591905056fea2646970667358221220826286baa5e2056c22be63f1fa7c05fb01bb158510356fb7ebb16f0da1edcc7564736f6c634300081c0033";

  
      type CertificateRegistryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CertificateRegistryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CertificateRegistry__factory extends ContractFactory {
    
      constructor(...args: CertificateRegistryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CertificateRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CertificateRegistry__factory {
      return super.connect(runner) as CertificateRegistry__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CertificateRegistryInterface {
      return new Interface(_abi) as CertificateRegistryInterface;
    }
    
    override attach(address: string | Addressable): CertificateRegistry {
      return super.attach(address) as CertificateRegistry;
    }
  static connect(address: string, runner?: ContractRunner | null): CertificateRegistry {
      return new Contract(address, _abi, runner) as unknown as CertificateRegistry;
    }
  }

  
  